-- -- local lsp_dir = vim.fn.stdpath("config") .. "/lua/config/lsp"
-- -- local enabled_servers = {}
-- --
-- -- for _, file in ipairs(vim.fn.readdir(lsp_dir)) do
-- --   local name = file:match("^(.*)%.lua$")
-- --   if name then
-- --     print("Loading LSP configuration for: " .. name)
-- --     require("config.lsp." .. name)
-- --     table.insert(enabled_servers, name)
-- --   end
-- -- end
-- --
-- -- vim.lsp.enable(enabled_servers)
--
-- vim.lsp.enable({
--   "clangd",
--   "docker_compose_language_service",
--   "dockerls",
--   "eslint",
--   "lua_ls",
--   "marksman",
--   "pyright",
--   "rust_analyzer",
--   "volar",
--   "vtsls",
-- })
--
-- vim.diagnostic.config({
--   virtual_text = true,
--   underline = true,
--   update_in_insert = false,
--   severity_sort = true,
--   float = {
--     border = "rounded",
--     source = true,
--   },
--   signs = {
--     text = {
--       [vim.diagnostic.severity.ERROR] = "󰅚 ",
--       [vim.diagnostic.severity.WARN] = "󰀪 ",
--       [vim.diagnostic.severity.INFO] = "󰋽 ",
--       [vim.diagnostic.severity.HINT] = "󰌶 ",
--     },
--     numhl = {
--       [vim.diagnostic.severity.ERROR] = "ErrorMsg",
--       [vim.diagnostic.severity.WARN] = "WarningMsg",
--     },
--   },
-- })
-- -- Extras
--
-- local function restart_lsp(bufnr)
--   bufnr = bufnr or vim.api.nvim_get_current_buf()
--   local clients
--   if vim.lsp.get_clients then
--     clients = vim.lsp.get_clients({ bufnr = bufnr })
--   else
--     ---@diagnostic disable-next-line: deprecated
--     clients = vim.lsp.get_active_clients({ bufnr = bufnr })
--   end
--
--   for _, client in ipairs(clients) do
--     vim.lsp.stop_client(client.id)
--   end
--
--   vim.defer_fn(function()
--     vim.cmd("edit")
--   end, 100)
-- end
--
-- vim.api.nvim_create_user_command("LspRestart", function()
--   restart_lsp()
-- end, {})
--
-- local function lsp_status()
--   local bufnr = vim.api.nvim_get_current_buf()
--   local clients = vim.lsp.get_clients and vim.lsp.get_clients({ bufnr = bufnr })
--     or vim.lsp.get_active_clients({ bufnr = bufnr })
--
--   if #clients == 0 then
--     print("󰅚 No LSP clients attached")
--     return
--   end
--
--   print("󰒋 LSP Status for buffer " .. bufnr .. ":")
--   print("─────────────────────────────────")
--
--   for i, client in ipairs(clients) do
--     print(string.format("󰌘 Client %d: %s (ID: %d)", i, client.name, client.id))
--     print("  Root: " .. (client.config.root_dir or "N/A"))
--     print("  Filetypes: " .. table.concat(client.config.filetypes or {}, ", "))
--
--     -- Check capabilities
--     local caps = client.server_capabilities
--     local features = {}
--     if caps.completionProvider then
--       table.insert(features, "completion")
--     end
--     if caps.hoverProvider then
--       table.insert(features, "hover")
--     end
--     if caps.definitionProvider then
--       table.insert(features, "definition")
--     end
--     if caps.referencesProvider then
--       table.insert(features, "references")
--     end
--     if caps.renameProvider then
--       table.insert(features, "rename")
--     end
--     if caps.codeActionProvider then
--       table.insert(features, "code_action")
--     end
--     if caps.documentFormattingProvider then
--       table.insert(features, "formatting")
--     end
--
--     print("  Features: " .. table.concat(features, ", "))
--     print("")
--   end
-- end
--
-- vim.api.nvim_create_user_command("LspStatus", lsp_status, { desc = "Show detailed LSP status" })
--
-- local function check_lsp_capabilities()
--   local bufnr = vim.api.nvim_get_current_buf()
--   local clients = vim.lsp.get_clients and vim.lsp.get_clients({ bufnr = bufnr })
--     or vim.lsp.get_active_clients({ bufnr = bufnr })
--
--   if #clients == 0 then
--     print("No LSP clients attached")
--     return
--   end
--
--   for _, client in ipairs(clients) do
--     print("Capabilities for " .. client.name .. ":")
--     local caps = client.server_capabilities
--
--     local capability_list = {
--       { "Completion", caps.completionProvider },
--       { "Hover", caps.hoverProvider },
--       { "Signature Help", caps.signatureHelpProvider },
--       { "Go to Definition", caps.definitionProvider },
--       { "Go to Declaration", caps.declarationProvider },
--       { "Go to Implementation", caps.implementationProvider },
--       { "Go to Type Definition", caps.typeDefinitionProvider },
--       { "Find References", caps.referencesProvider },
--       { "Document Highlight", caps.documentHighlightProvider },
--       { "Document Symbol", caps.documentSymbolProvider },
--       { "Workspace Symbol", caps.workspaceSymbolProvider },
--       { "Code Action", caps.codeActionProvider },
--       { "Code Lens", caps.codeLensProvider },
--       { "Document Formatting", caps.documentFormattingProvider },
--       { "Document Range Formatting", caps.documentRangeFormattingProvider },
--       { "Rename", caps.renameProvider },
--       { "Folding Range", caps.foldingRangeProvider },
--       { "Selection Range", caps.selectionRangeProvider },
--     }
--
--     for _, cap in ipairs(capability_list) do
--       local status = cap[2] and "✓" or "✗"
--       print(string.format("  %s %s", status, cap[1]))
--     end
--     print("")
--   end
-- end
--
-- vim.api.nvim_create_user_command("LspCapabilities", check_lsp_capabilities, { desc = "Show LSP capabilities" })
--
-- local function lsp_diagnostics_info()
--   local bufnr = vim.api.nvim_get_current_buf()
--   local diagnostics = vim.diagnostic.get(bufnr)
--
--   local counts = { ERROR = 0, WARN = 0, INFO = 0, HINT = 0 }
--
--   for _, diagnostic in ipairs(diagnostics) do
--     local severity = vim.diagnostic.severity[diagnostic.severity]
--     counts[severity] = counts[severity] + 1
--   end
--
--   print("󰒡 Diagnostics for current buffer:")
--   print("  Errors: " .. counts.ERROR)
--   print("  Warnings: " .. counts.WARN)
--   print("  Info: " .. counts.INFO)
--   print("  Hints: " .. counts.HINT)
--   print("  Total: " .. #diagnostics)
-- end
--
-- vim.api.nvim_create_user_command("LspDiagnostics", lsp_diagnostics_info, { desc = "Show LSP diagnostics count" })
--
-- local function lsp_info()
--   local bufnr = vim.api.nvim_get_current_buf()
--   local clients = vim.lsp.get_clients and vim.lsp.get_clients({ bufnr = bufnr })
--     or vim.lsp.get_active_clients({ bufnr = bufnr })
--
--   print("═══════════════════════════════════")
--   print("           LSP INFORMATION          ")
--   print("═══════════════════════════════════\n")
--
--   -- Basic info
--   print("󰈙  Language client log: " .. vim.lsp.get_log_path())
--   print("󰈔  Detected filetype    : " .. vim.bo.filetype)
--   print("󰈮  Buffer               : " .. bufnr)
--   print("󰈔  Root directory       : " .. (vim.fn.getcwd() or "N/A") .. "\n")
--
--   if #clients == 0 then
--     print("󰅚 No LSP clients attached to buffer " .. bufnr .. "\n")
--     print("Possible reasons:")
--     print("  • No language server installed for this filetype")
--     print("  • Language server not configured or not started")
--     print("  • Not in a project root directory")
--     print("  • File type not recognized or supported")
--     return
--   end
--
--   print("󰒋 LSP clients attached to buffer " .. bufnr .. ":")
--   print(
--     "─────────────────────────────────────────────────"
--   )
--
--   for i, client in ipairs(clients) do
--     print(string.format("󰌘  Client %d: %s", i, client.name))
--     print("    ID         : " .. client.id)
--     print("    Root Dir   : " .. (client.config.root_dir or "Not set"))
--     print("    Command    : " .. table.concat(client.config.cmd or {}, " "))
--     print("    Filetypes  : " .. table.concat(client.config.filetypes or {}, ", "))
--     print("    Status     : " .. (client.is_stopped and client:is_stopped() and "󰅚 Stopped" or "󰄬 Running"))
--
--     if client.workspace_folders and #client.workspace_folders > 0 then
--       print("    Workspace Folders:")
--       for _, folder in ipairs(client.workspace_folders) do
--         print("      • " .. (folder.name or folder.uri or ""))
--       end
--     end
--
--     local attached_buffers = vim.tbl_keys(client.attached_buffers or {})
--     print("    Attached Buffers : " .. #attached_buffers)
--
--     -- Capabilities summary
--     local caps = client.server_capabilities or {}
--     local features = {}
--     if caps.completionProvider then
--       table.insert(features, "completion")
--     end
--     if caps.hoverProvider then
--       table.insert(features, "hover")
--     end
--     if caps.definitionProvider then
--       table.insert(features, "definition")
--     end
--     if caps.declarationProvider then
--       table.insert(features, "declaration")
--     end
--     if caps.implementationProvider then
--       table.insert(features, "implementation")
--     end
--     if caps.typeDefinitionProvider then
--       table.insert(features, "type_definition")
--     end
--     if caps.referencesProvider then
--       table.insert(features, "references")
--     end
--     if caps.renameProvider then
--       table.insert(features, "rename")
--     end
--     if caps.documentHighlightProvider then
--       table.insert(features, "document_highlight")
--     end
--     if caps.documentFormattingProvider then
--       table.insert(features, "formatting")
--     end
--     if caps.codeActionProvider then
--       table.insert(features, "code_action")
--     end
--     if caps.documentSymbolProvider then
--       table.insert(features, "document_symbols")
--     end
--     if caps.workspaceSymbolProvider then
--       table.insert(features, "workspace_symbols")
--     end
--
--     if #features > 0 then
--       print("    Capabilities      : " .. table.concat(features, ", "))
--     end
--
--     print("    Config            :")
--     for _, line in ipairs(vim.split(vim.inspect(client.config), "\n")) do
--       print("      " .. line)
--     end
--
--     print("")
--   end
--
--   -- Diagnostics
--   local diagnostics = vim.diagnostic.get(bufnr)
--   if #diagnostics > 0 then
--     local counts = { [1] = 0, [2] = 0, [3] = 0, [4] = 0 }
--     for _, d in ipairs(diagnostics) do
--       counts[d.severity] = counts[d.severity] + 1
--     end
--     print("󰒡 Diagnostics Summary:")
--     print("  󰅚 Errors   : " .. counts[1])
--     print("  󰀪 Warnings : " .. counts[2])
--     print("  󰋽 Info     : " .. counts[3])
--     print("  󰌶 Hints    : " .. counts[4])
--     print("  Total      : " .. #diagnostics)
--   else
--     print("󰄬 No diagnostics reported.")
--   end
--
--   print("\nUse :LspLog to view detailed logs")
--   print("Use :LspCapabilities for full capability list")
-- end
--
-- vim.api.nvim_create_user_command("LspInfo", lsp_info, { desc = "Show detailed LSP information" })
--
-- -- Create command
-- vim.api.nvim_create_user_command("LspInfo", lsp_info, { desc = "Show comprehensive LSP information" })
--
-- local function lsp_status_short()
--   local bufnr = vim.api.nvim_get_current_buf()
--   local clients = vim.lsp.get_clients and vim.lsp.get_clients({ bufnr = bufnr })
--     or vim.lsp.get_active_clients({ bufnr = bufnr })
--
--   if #clients == 0 then
--     return "" -- Return empty string when no LSP
--   end
--
--   local names = {}
--   for _, client in ipairs(clients) do
--     table.insert(names, client.name)
--   end
--
--   return "󰒋 " .. table.concat(names, ",")
-- end
--
-- local function git_branch()
--   local ok, handle = pcall(io.popen, "git branch --show-current 2>/dev/null")
--   if not ok or not handle then
--     return ""
--   end
--   local branch = handle:read("*a")
--   handle:close()
--   if branch and branch ~= "" then
--     branch = branch:gsub("\n", "")
--     return "󰊢 " .. branch
--   end
--   return ""
-- end
-- -- Safe wrapper functions for statusline
-- local function safe_git_branch()
--   local ok, result = pcall(git_branch)
--   return ok and result or ""
-- end
--
-- local function safe_lsp_status()
--   local ok, result = pcall(lsp_status_short)
--   return ok and result or ""
-- end
--
-- _G.git_branch = safe_git_branch
-- _G.lsp_status = safe_lsp_status
--
-- -- THEN set the statusline
-- vim.opt.statusline = table.concat({
--   "%{v:lua.git_branch()}", -- Git branch
--   "%f", -- File name
--   "%m", -- Modified flag
--   "%r", -- Readonly flag
--   "%=", -- Right align
--   "%{v:lua.lsp_status()}", -- LSP status
--   " %l:%c", -- Line:Column
--   " %p%%", -- Percentage through file
-- }, " ")
